### ISSUE TITLE
请问 indexes.json是什么样的

### ISSUE THREAD

**Issue by Attiv** [in3102/utools-php-doc#1]
我看 preload.js里
```
require('./indexes.json')
```
但是我在仓库、文档和社区里都没有找到 indexes.json的demo，麻烦可以告知一下吗？ 多谢

**Comment by in3102** [comment]
这个是生成的
[{"t":"APCIterator::__construct","p":"php-chunked-xhtml/apciterator.construct.html","d":"构造一个 APCIterator 迭代器对象"},{"t":"APCIterator::current","p":"php-chunked-xhtml/apciterator.current.html","d":"获取当前项"}]
